"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { heroSlides } from "@/lib/data";
import { ChevronLeft, ChevronRight } from "./icons";

const AUTOPLAY = 6500;

export default function Hero() {
  const [index, setIndex] = useState(0);
  const count = heroSlides.length;
  const go = useCallback(
    (dir: number) => setIndex((i) => (i + dir + count) % count),
    [count],
  );

  useEffect(() => {
    const t = setInterval(() => setIndex((i) => (i + 1) % count), AUTOPLAY);
    return () => clearInterval(t);
  }, [count]);

  // Below 640px each slide swaps to a purpose-built portrait composite
  // (lib/data.ts `mobileImage`, generated by scripts/build-mobile-hero-crops.js)
  // instead of cropping the landscape banner — matching how
  // auto.mahindra.com itself ships separate portrait creative per
  // campaign for mobile. Those composites are different shapes per
  // slide, so on mobile the hero's height follows the active slide's
  // own aspect ratio instead of a fixed box, which would just crop them
  // again.
  const [mobile, setMobile] = useState(false);
  useEffect(() => {
    const mq = window.matchMedia("(max-width: 639px)");
    const sync = () => setMobile(mq.matches);
    sync();
    mq.addEventListener("change", sync);
    return () => mq.removeEventListener("change", sync);
  }, []);

  const active = heroSlides[index];

  return (
    <section
      id="home"
      className="relative scroll-mt-24 overflow-hidden bg-brand-deep"
      style={{ marginTop: "60px" }} /* offset for 2-row nav */
    >
      {/* Cinematic banner carousel, matching auto.mahindra.com's own hero
          treatment exactly: the official campaign creative already carries
          the headline/graphics baked into the photo, so each slide is shown
          clean and clickable, with only a slim progress bar and minimal
          arrow controls overlaid. */}
      <div
        className="relative w-full aspect-[16/9] lg:aspect-[21/9]"
        style={mobile && active.mobileImage ? { aspectRatio: active.mobileAspect } : undefined}
      >
        {heroSlides.map((slide, i) => (
          <Link
            key={slide.model + i}
            href={slide.href}
            aria-hidden={i === index ? undefined : true}
            tabIndex={i === index ? undefined : -1}
            className="absolute inset-0 transition-opacity duration-[900ms] ease-out"
            style={{ opacity: i === index ? 1 : 0, pointerEvents: i === index ? "auto" : "none" }}
          >
            {/* Two <Image>s per slide (mobile composite vs. desktop crop)
                so next/image only ever requests the one actually shown —
                toggled with plain CSS breakpoints, not JS, so there's no
                flash of the wrong image while `mobile` resolves. Slides
                with no usable mobile composite (see lib/data.ts) skip the
                first <Image> entirely and show the desktop crop at every
                width instead of a broken portrait composite. */}
            {slide.mobileImage && (
              <Image
                src={slide.mobileImage}
                alt={slide.alt}
                title={slide.alt}
                fill
                priority={i === 0}
                sizes="(min-width: 640px) 0px, 100vw"
                className="object-contain sm:hidden"
              />
            )}
            <Image
              src={slide.image}
              alt={slide.alt}
              title={slide.alt}
              fill
              priority={i === 0}
              sizes={slide.mobileImage ? "(max-width: 639px) 0px, 100vw" : "100vw"}
              // Per-slide horizontal focus (lib/data.ts `heroFocusX`): these
              // banners aren't framed with the headline centred, so a plain
              // "center" crop clips the headline or disclaimer text off one
              // edge once the box is narrower than the source banner.
              style={{ objectPosition: `${slide.heroFocusX ?? 50}% 35%` }}
              className={slide.mobileImage ? "hidden object-cover sm:block" : "block object-cover"}
            />
          </Link>
        ))}

        <h1 className="sr-only">
          New Mahindra Cars, Test Drives &amp; Authorised Service Across
          Thane and Navi Mumbai | Mahindra Modi
        </h1>

        {/* Arrow controls — left and right edges, vertically centred, kept
            inside the same horizontal safe-zone padding as the rest of the
            hero overlay so they never crowd the notch/rounded-corner area
            on narrow phones. No circular background so they don't sit over
            the hero text baked into the creative. */}
        <div className="hero-safe pointer-events-none absolute inset-0 flex items-center justify-between">
          <button
            aria-label="Previous slide"
            onClick={() => go(-1)}
            className="pointer-events-auto z-10 text-white/80 transition-colors hover:text-white"
          >
            <ChevronLeft className="h-7 w-7" />
          </button>
          <button
            aria-label="Next slide"
            onClick={() => go(1)}
            className="pointer-events-auto z-10 text-white/80 transition-colors hover:text-white"
          >
            <ChevronRight className="h-7 w-7" />
          </button>
        </div>

        {/* Slim progress bar, bottom-left, anchored inside the safe zone so
            it scales its clearance with viewport height instead of a fixed
            offset that can sit too close to the edge on short screens. */}
        <div className="hero-safe pointer-events-none absolute inset-x-0 bottom-0 flex">
          <div className="h-[3px] w-32 overflow-hidden rounded-full bg-white/30 sm:w-48">
            <span
              key={index}
              className="block h-full rounded-full bg-white"
              style={{ width: "0%", animation: `hero-progress ${AUTOPLAY}ms linear forwards` }}
            />
          </div>
        </div>
      </div>
    </section>
  );
}
