/* All ITU-assigned country calling codes, with the flag derived from the
   ISO 3166-1 alpha-2 code (rather than hand-typed emoji, which is easy to
   get wrong) and a min/max national number length used to validate input.
   Lengths are typical mobile-subscriber-number lengths (excluding the
   country code and any leading trunk "0"); a handful of countries support
   more than one length, hence the min/max range rather than a single value. */

const flagFromIso = (iso: string) =>
  String.fromCodePoint(...[...iso.toUpperCase()].map((c) => 127397 + c.charCodeAt(0)));

type RawCountry = {
  iso: string;
  name: string;
  code: string;
  min: number;
  max: number;
};

// Sorted alphabetically by name, except India is pinned first as the default.
const raw: RawCountry[] = [
  { iso: "IN", name: "India", code: "+91", min: 10, max: 10 },
  { iso: "AF", name: "Afghanistan", code: "+93", min: 9, max: 9 },
  { iso: "AL", name: "Albania", code: "+355", min: 9, max: 9 },
  { iso: "DZ", name: "Algeria", code: "+213", min: 9, max: 9 },
  { iso: "AD", name: "Andorra", code: "+376", min: 6, max: 6 },
  { iso: "AO", name: "Angola", code: "+244", min: 9, max: 9 },
  { iso: "AG", name: "Antigua and Barbuda", code: "+1268", min: 7, max: 7 },
  { iso: "AR", name: "Argentina", code: "+54", min: 10, max: 10 },
  { iso: "AM", name: "Armenia", code: "+374", min: 8, max: 8 },
  { iso: "AU", name: "Australia", code: "+61", min: 9, max: 9 },
  { iso: "AT", name: "Austria", code: "+43", min: 10, max: 11 },
  { iso: "AZ", name: "Azerbaijan", code: "+994", min: 9, max: 9 },
  { iso: "BS", name: "Bahamas", code: "+1242", min: 7, max: 7 },
  { iso: "BH", name: "Bahrain", code: "+973", min: 8, max: 8 },
  { iso: "BD", name: "Bangladesh", code: "+880", min: 10, max: 10 },
  { iso: "BB", name: "Barbados", code: "+1246", min: 7, max: 7 },
  { iso: "BY", name: "Belarus", code: "+375", min: 9, max: 9 },
  { iso: "BE", name: "Belgium", code: "+32", min: 9, max: 9 },
  { iso: "BZ", name: "Belize", code: "+501", min: 7, max: 7 },
  { iso: "BJ", name: "Benin", code: "+229", min: 8, max: 8 },
  { iso: "BT", name: "Bhutan", code: "+975", min: 8, max: 8 },
  { iso: "BO", name: "Bolivia", code: "+591", min: 8, max: 8 },
  { iso: "BA", name: "Bosnia and Herzegovina", code: "+387", min: 8, max: 8 },
  { iso: "BW", name: "Botswana", code: "+267", min: 8, max: 8 },
  { iso: "BR", name: "Brazil", code: "+55", min: 10, max: 11 },
  { iso: "BN", name: "Brunei", code: "+673", min: 7, max: 7 },
  { iso: "BG", name: "Bulgaria", code: "+359", min: 8, max: 9 },
  { iso: "BF", name: "Burkina Faso", code: "+226", min: 8, max: 8 },
  { iso: "BI", name: "Burundi", code: "+257", min: 8, max: 8 },
  { iso: "KH", name: "Cambodia", code: "+855", min: 8, max: 9 },
  { iso: "CM", name: "Cameroon", code: "+237", min: 9, max: 9 },
  { iso: "CA", name: "Canada", code: "+1", min: 10, max: 10 },
  { iso: "CV", name: "Cape Verde", code: "+238", min: 7, max: 7 },
  { iso: "CF", name: "Central African Republic", code: "+236", min: 8, max: 8 },
  { iso: "TD", name: "Chad", code: "+235", min: 8, max: 8 },
  { iso: "CL", name: "Chile", code: "+56", min: 9, max: 9 },
  { iso: "CN", name: "China", code: "+86", min: 11, max: 11 },
  { iso: "CO", name: "Colombia", code: "+57", min: 10, max: 10 },
  { iso: "KM", name: "Comoros", code: "+269", min: 7, max: 7 },
  { iso: "CG", name: "Congo", code: "+242", min: 9, max: 9 },
  { iso: "CD", name: "Congo (DRC)", code: "+243", min: 9, max: 9 },
  { iso: "CR", name: "Costa Rica", code: "+506", min: 8, max: 8 },
  { iso: "HR", name: "Croatia", code: "+385", min: 8, max: 9 },
  { iso: "CU", name: "Cuba", code: "+53", min: 8, max: 8 },
  { iso: "CY", name: "Cyprus", code: "+357", min: 8, max: 8 },
  { iso: "CZ", name: "Czech Republic", code: "+420", min: 9, max: 9 },
  { iso: "DK", name: "Denmark", code: "+45", min: 8, max: 8 },
  { iso: "DJ", name: "Djibouti", code: "+253", min: 8, max: 8 },
  { iso: "DM", name: "Dominica", code: "+1767", min: 7, max: 7 },
  { iso: "DO", name: "Dominican Republic", code: "+1809", min: 7, max: 7 },
  { iso: "EC", name: "Ecuador", code: "+593", min: 9, max: 9 },
  { iso: "EG", name: "Egypt", code: "+20", min: 10, max: 10 },
  { iso: "SV", name: "El Salvador", code: "+503", min: 8, max: 8 },
  { iso: "GQ", name: "Equatorial Guinea", code: "+240", min: 9, max: 9 },
  { iso: "ER", name: "Eritrea", code: "+291", min: 7, max: 7 },
  { iso: "EE", name: "Estonia", code: "+372", min: 7, max: 8 },
  { iso: "SZ", name: "Eswatini", code: "+268", min: 8, max: 8 },
  { iso: "ET", name: "Ethiopia", code: "+251", min: 9, max: 9 },
  { iso: "FJ", name: "Fiji", code: "+679", min: 7, max: 7 },
  { iso: "FI", name: "Finland", code: "+358", min: 9, max: 10 },
  { iso: "FR", name: "France", code: "+33", min: 9, max: 9 },
  { iso: "GA", name: "Gabon", code: "+241", min: 8, max: 8 },
  { iso: "GM", name: "Gambia", code: "+220", min: 7, max: 7 },
  { iso: "GE", name: "Georgia", code: "+995", min: 9, max: 9 },
  { iso: "DE", name: "Germany", code: "+49", min: 10, max: 11 },
  { iso: "GH", name: "Ghana", code: "+233", min: 9, max: 9 },
  { iso: "GR", name: "Greece", code: "+30", min: 10, max: 10 },
  { iso: "GD", name: "Grenada", code: "+1473", min: 7, max: 7 },
  { iso: "GT", name: "Guatemala", code: "+502", min: 8, max: 8 },
  { iso: "GN", name: "Guinea", code: "+224", min: 8, max: 9 },
  { iso: "GW", name: "Guinea-Bissau", code: "+245", min: 7, max: 7 },
  { iso: "GY", name: "Guyana", code: "+592", min: 7, max: 7 },
  { iso: "HT", name: "Haiti", code: "+509", min: 8, max: 8 },
  { iso: "HN", name: "Honduras", code: "+504", min: 8, max: 8 },
  { iso: "HK", name: "Hong Kong", code: "+852", min: 8, max: 8 },
  { iso: "HU", name: "Hungary", code: "+36", min: 9, max: 9 },
  { iso: "IS", name: "Iceland", code: "+354", min: 7, max: 7 },
  { iso: "ID", name: "Indonesia", code: "+62", min: 9, max: 11 },
  { iso: "IR", name: "Iran", code: "+98", min: 10, max: 10 },
  { iso: "IQ", name: "Iraq", code: "+964", min: 10, max: 10 },
  { iso: "IE", name: "Ireland", code: "+353", min: 9, max: 9 },
  { iso: "IL", name: "Israel", code: "+972", min: 9, max: 9 },
  { iso: "IT", name: "Italy", code: "+39", min: 9, max: 10 },
  { iso: "JM", name: "Jamaica", code: "+1876", min: 7, max: 7 },
  { iso: "JP", name: "Japan", code: "+81", min: 10, max: 10 },
  { iso: "JO", name: "Jordan", code: "+962", min: 9, max: 9 },
  { iso: "KZ", name: "Kazakhstan", code: "+7", min: 10, max: 10 },
  { iso: "KE", name: "Kenya", code: "+254", min: 9, max: 9 },
  { iso: "KI", name: "Kiribati", code: "+686", min: 5, max: 8 },
  { iso: "KW", name: "Kuwait", code: "+965", min: 8, max: 8 },
  { iso: "KG", name: "Kyrgyzstan", code: "+996", min: 9, max: 9 },
  { iso: "LA", name: "Laos", code: "+856", min: 8, max: 10 },
  { iso: "LV", name: "Latvia", code: "+371", min: 8, max: 8 },
  { iso: "LB", name: "Lebanon", code: "+961", min: 7, max: 8 },
  { iso: "LS", name: "Lesotho", code: "+266", min: 8, max: 8 },
  { iso: "LR", name: "Liberia", code: "+231", min: 7, max: 9 },
  { iso: "LY", name: "Libya", code: "+218", min: 9, max: 9 },
  { iso: "LI", name: "Liechtenstein", code: "+423", min: 7, max: 7 },
  { iso: "LT", name: "Lithuania", code: "+370", min: 8, max: 8 },
  { iso: "LU", name: "Luxembourg", code: "+352", min: 9, max: 9 },
  { iso: "MO", name: "Macau", code: "+853", min: 8, max: 8 },
  { iso: "MG", name: "Madagascar", code: "+261", min: 9, max: 9 },
  { iso: "MW", name: "Malawi", code: "+265", min: 9, max: 9 },
  { iso: "MY", name: "Malaysia", code: "+60", min: 9, max: 10 },
  { iso: "MV", name: "Maldives", code: "+960", min: 7, max: 7 },
  { iso: "ML", name: "Mali", code: "+223", min: 8, max: 8 },
  { iso: "MT", name: "Malta", code: "+356", min: 8, max: 8 },
  { iso: "MH", name: "Marshall Islands", code: "+692", min: 7, max: 7 },
  { iso: "MR", name: "Mauritania", code: "+222", min: 8, max: 8 },
  { iso: "MU", name: "Mauritius", code: "+230", min: 7, max: 8 },
  { iso: "MX", name: "Mexico", code: "+52", min: 10, max: 10 },
  { iso: "FM", name: "Micronesia", code: "+691", min: 7, max: 7 },
  { iso: "MD", name: "Moldova", code: "+373", min: 8, max: 8 },
  { iso: "MC", name: "Monaco", code: "+377", min: 8, max: 9 },
  { iso: "MN", name: "Mongolia", code: "+976", min: 8, max: 8 },
  { iso: "ME", name: "Montenegro", code: "+382", min: 8, max: 8 },
  { iso: "MA", name: "Morocco", code: "+212", min: 9, max: 9 },
  { iso: "MZ", name: "Mozambique", code: "+258", min: 9, max: 9 },
  { iso: "MM", name: "Myanmar", code: "+95", min: 8, max: 10 },
  { iso: "NA", name: "Namibia", code: "+264", min: 9, max: 9 },
  { iso: "NR", name: "Nauru", code: "+674", min: 7, max: 7 },
  { iso: "NP", name: "Nepal", code: "+977", min: 10, max: 10 },
  { iso: "NL", name: "Netherlands", code: "+31", min: 9, max: 9 },
  { iso: "NZ", name: "New Zealand", code: "+64", min: 9, max: 10 },
  { iso: "NI", name: "Nicaragua", code: "+505", min: 8, max: 8 },
  { iso: "NE", name: "Niger", code: "+227", min: 8, max: 8 },
  { iso: "NG", name: "Nigeria", code: "+234", min: 10, max: 10 },
  { iso: "KP", name: "North Korea", code: "+850", min: 8, max: 10 },
  { iso: "MK", name: "North Macedonia", code: "+389", min: 8, max: 8 },
  { iso: "NO", name: "Norway", code: "+47", min: 8, max: 8 },
  { iso: "OM", name: "Oman", code: "+968", min: 8, max: 8 },
  { iso: "PK", name: "Pakistan", code: "+92", min: 10, max: 10 },
  { iso: "PW", name: "Palau", code: "+680", min: 7, max: 7 },
  { iso: "PS", name: "Palestine", code: "+970", min: 9, max: 9 },
  { iso: "PA", name: "Panama", code: "+507", min: 7, max: 8 },
  { iso: "PG", name: "Papua New Guinea", code: "+675", min: 7, max: 8 },
  { iso: "PY", name: "Paraguay", code: "+595", min: 9, max: 9 },
  { iso: "PE", name: "Peru", code: "+51", min: 9, max: 9 },
  { iso: "PH", name: "Philippines", code: "+63", min: 10, max: 10 },
  { iso: "PL", name: "Poland", code: "+48", min: 9, max: 9 },
  { iso: "PT", name: "Portugal", code: "+351", min: 9, max: 9 },
  { iso: "QA", name: "Qatar", code: "+974", min: 8, max: 8 },
  { iso: "RO", name: "Romania", code: "+40", min: 9, max: 9 },
  { iso: "RU", name: "Russia", code: "+7", min: 10, max: 10 },
  { iso: "RW", name: "Rwanda", code: "+250", min: 9, max: 9 },
  { iso: "KN", name: "Saint Kitts and Nevis", code: "+1869", min: 7, max: 7 },
  { iso: "LC", name: "Saint Lucia", code: "+1758", min: 7, max: 7 },
  { iso: "VC", name: "Saint Vincent and the Grenadines", code: "+1784", min: 7, max: 7 },
  { iso: "WS", name: "Samoa", code: "+685", min: 5, max: 7 },
  { iso: "SM", name: "San Marino", code: "+378", min: 6, max: 10 },
  { iso: "ST", name: "Sao Tome and Principe", code: "+239", min: 7, max: 7 },
  { iso: "SA", name: "Saudi Arabia", code: "+966", min: 9, max: 9 },
  { iso: "SN", name: "Senegal", code: "+221", min: 9, max: 9 },
  { iso: "RS", name: "Serbia", code: "+381", min: 8, max: 9 },
  { iso: "SC", name: "Seychelles", code: "+248", min: 7, max: 7 },
  { iso: "SL", name: "Sierra Leone", code: "+232", min: 8, max: 8 },
  { iso: "SG", name: "Singapore", code: "+65", min: 8, max: 8 },
  { iso: "SK", name: "Slovakia", code: "+421", min: 9, max: 9 },
  { iso: "SI", name: "Slovenia", code: "+386", min: 8, max: 8 },
  { iso: "SB", name: "Solomon Islands", code: "+677", min: 5, max: 7 },
  { iso: "SO", name: "Somalia", code: "+252", min: 7, max: 9 },
  { iso: "ZA", name: "South Africa", code: "+27", min: 9, max: 9 },
  { iso: "KR", name: "South Korea", code: "+82", min: 9, max: 10 },
  { iso: "SS", name: "South Sudan", code: "+211", min: 9, max: 9 },
  { iso: "ES", name: "Spain", code: "+34", min: 9, max: 9 },
  { iso: "LK", name: "Sri Lanka", code: "+94", min: 9, max: 9 },
  { iso: "SD", name: "Sudan", code: "+249", min: 9, max: 9 },
  { iso: "SR", name: "Suriname", code: "+597", min: 6, max: 7 },
  { iso: "SE", name: "Sweden", code: "+46", min: 9, max: 9 },
  { iso: "CH", name: "Switzerland", code: "+41", min: 9, max: 9 },
  { iso: "SY", name: "Syria", code: "+963", min: 9, max: 9 },
  { iso: "TW", name: "Taiwan", code: "+886", min: 9, max: 9 },
  { iso: "TJ", name: "Tajikistan", code: "+992", min: 9, max: 9 },
  { iso: "TZ", name: "Tanzania", code: "+255", min: 9, max: 9 },
  { iso: "TH", name: "Thailand", code: "+66", min: 9, max: 9 },
  { iso: "TL", name: "Timor-Leste", code: "+670", min: 7, max: 8 },
  { iso: "TG", name: "Togo", code: "+228", min: 8, max: 8 },
  { iso: "TO", name: "Tonga", code: "+676", min: 5, max: 7 },
  { iso: "TT", name: "Trinidad and Tobago", code: "+1868", min: 7, max: 7 },
  { iso: "TN", name: "Tunisia", code: "+216", min: 8, max: 8 },
  { iso: "TR", name: "Turkey", code: "+90", min: 10, max: 10 },
  { iso: "TM", name: "Turkmenistan", code: "+993", min: 8, max: 8 },
  { iso: "TV", name: "Tuvalu", code: "+688", min: 5, max: 6 },
  { iso: "UG", name: "Uganda", code: "+256", min: 9, max: 9 },
  { iso: "UA", name: "Ukraine", code: "+380", min: 9, max: 9 },
  { iso: "AE", name: "United Arab Emirates", code: "+971", min: 9, max: 9 },
  { iso: "GB", name: "United Kingdom", code: "+44", min: 10, max: 10 },
  { iso: "US", name: "United States", code: "+1", min: 10, max: 10 },
  { iso: "UY", name: "Uruguay", code: "+598", min: 8, max: 8 },
  { iso: "UZ", name: "Uzbekistan", code: "+998", min: 9, max: 9 },
  { iso: "VU", name: "Vanuatu", code: "+678", min: 5, max: 7 },
  { iso: "VA", name: "Vatican City", code: "+379", min: 10, max: 10 },
  { iso: "VE", name: "Venezuela", code: "+58", min: 10, max: 10 },
  { iso: "VN", name: "Vietnam", code: "+84", min: 9, max: 10 },
  { iso: "YE", name: "Yemen", code: "+967", min: 9, max: 9 },
  { iso: "ZM", name: "Zambia", code: "+260", min: 9, max: 9 },
  { iso: "ZW", name: "Zimbabwe", code: "+263", min: 9, max: 9 },
];

export const countryCodes = raw.map((c) => ({
  ...c,
  flag: flagFromIso(c.iso),
}));

export type CountryCode = (typeof countryCodes)[number];
